### ISSUE TITLE
Authorization Issue

### ISSUE THREAD

**Issue by krishnadean** [audioBoom/api#10]
Hi @jdelStrother 
I am integrating Audio Boom API but getting error on initial stage
Authentication URL : https://api.audioboom.com/oauth/authorize?response_type=code&client_id=xxxxxxxxxxxxxxxx&redirect_uri=http://my-domain.com/user/share/abcallback
When i call above URL then getting an error : "Cannot find request token"
I have also checked the given reference URL for OAuth 2.0 process.
Given Ref. URL : https://aaronparecki.com/oauth-2-simplified/#authorization

Please let me know, whatever is missing on Auth URL?

**Comment by jdelStrother** [comment]
Sorry about that - I think there was a bug causing your request to get handled as if it were OAuth1, not OAuth2.  Could you try now?

**Comment by krishnadean** [comment]
Hi @jdelStrother , It seems to be working fine now. If there will be any issue during other API integration then I will get in touch.
Thank you so much.
