### ISSUE TITLE
Access Token Issue

### ISSUE THREAD

**Issue by krishnadean** [audioBoom/api#11]
Hi @jdelStrother
I am having the issue, while trying to find the access token, Please check below screenshot.
I am following this document : https://aaronparecki.com/oauth-2-simplified/#authorization
![image](https://user-images.githubusercontent.com/27285282/31929042-f53c2a4a-b8b7-11e7-9ad7-536a1d415826.png)

**Comment by jdelStrother** [comment]
Hi there - sorry, it looks like we had a documentation bug at https://github.com/audioBoom/api/blob/master/sections/authentication.md.   Could you try again using `POST /oauth/token`, rather than `POST /oauth/access_token` ?

**Comment by krishnadean** [comment]
While trying `POST /oauth/token` then getting error message : 

> The request was rejected as it was missing or had bad required authentication information.

**Comment by jdelStrother** [comment]
Hi - I think you either need to include your client_secret, or a state parameter matching the cookie value, depending on your use case.   I'm just deployed a fix to give clearer error messages - give it another try?

**Comment by krishnadean** [comment]
I have received the below response.

```
[access_token] => 255cXXXXXXXXXXXX4f17b8
[token_type] => auth_code
[expires_in] => 6XXXXXXXXX9
[refresh_token] => 3XXXXXXXXXXXXXXX86
[created_at] => 15XXXXXX879
[scope] => ab
```
Is token_type fine according to you?

**Comment by jdelStrother** [comment]
Good catch, it should be Bearer.  Will be fixed shortly.
