### ISSUE TITLE
Are APIs available for?

### ISSUE THREAD

**Issue by krishnadean** [audioBoom/api#12]
Hi @jdelStrother ,
I need to perform the actions as given below.

1. Need to fetch the audio with their thumbnail via audioboom API for the audioboom authenticated user.
2. Need to push "likes" on audioboom, the "likes" gathered on audios fetched from Audioboom at our website for authenticated users.
3. Need to give the comment on audioboom for an audio from our website via audioboom API by the audioboom authenticated user.

Please make sure, Are audioboom APIs available for these actions, which i want to perform from a website?

**Comment by krishnadean** [comment]
Hi @jdelStrother , Waiting for your reply.

**Comment by jdelStrother** [comment]
Yes, see https://github.com/audioboom/api/blob/master/sections/audio_clips.md, https://github.com/audioboom/api/blob/master/sections/favourites.md, and https://github.com/audioboom/api/blob/master/sections/comments.md
