### ISSUE TITLE
i can not acess to GET /channels/*channel_id*/child_channels

### ISSUE THREAD

**Issue by Saikilito** [audioBoom/api#14]
it response for example:

{
"window": 60,
"version": 200,
"timestamp": 1554508961,
"api_warning": "You should include a version number in your API requests",
"body": {
"totals": {
"count": 0,
"offset": 0
},
"channels": []
}
}

**Comment by jdelStrother** [comment]
Which channel are you looking at?  It seems ok on, eg, https://api.audioboom.com/channels/1489701/child_channels

**Comment by Saikilito** [comment]
It seems that I was really clueless, I was drinking a particularly empty channel, i am sorry
