### ISSUE TITLE
What can I search for?

### ISSUE THREAD

**Issue by MastaBaba** [audioBoom/api#15]
I know I can do this to find clips close to a point:

`https://api.audioboom.com/audio_clips/located?api_version=1&find[latitude]=52.2&find[longitude]=4.5
`
I know the format for searches is this:

`find[query] = value`

I don't know what query parameters I can use. Where can I find a list? Is there an option to search for clips with a minimum length?

**Comment by jdelStrother** [comment]
Hi there - sorry if it's not obvious from the docs, it's a plain-text search.  For example: https://api.audioboom.com/audio_clips/located?api_version=1&find%5Blatitude%5D=52.2&find%5Blongitude%5D=4.5&find[query]=gladskin finds episodes that mention gladskin in the title or description.

**Comment by jdelStrother** [comment]
> Is there an option to search for clips with a minimum length?
and just to clarify - no, we don't have a way to filter by duration.

**Comment by MastaBaba** [comment]
Thanks for the clarification!
