### ISSUE TITLE
How to obtain category information?

### ISSUE THREAD

**Issue by MastaBaba** [audioBoom/api#5]
In the endpoints returning audio_clips, the audio_clips have a 'category_id' property. However, I don't see any endpoint that can give me information on what these category_ids represent.

How can I get information, through the API, of categories, by their category_id?

**Comment by jdelStrother** [comment]
Heya - take a look at https://github.com/audioBoom/api/blob/master/sections/categories.md.   eg `https://api.audioboom.com/categories`
