### ISSUE TITLE
GET /account with authenticated header triggers preflight request 

### ISSUE THREAD

**Issue by digitalillusion** [audioBoom/api#6]
Hello,

I've successfully obtained an access token from /token and I'm trying to use it to GET /account
However, if I add the following header
`Authorization: Bearer T0k3nH4shC0d3Her3`
a preflight (OPTIONS) request is sent supposedly because the server CORS filter did not accept the header.
I'm following [this OAuth guide](https://oauth.net/getting-started/) and that's why I'm sending such header. 
Is another way of accepting the access token implemented instead? I've tried adding query string parameters like _access_token_ or _token_ but I'm getting 403 Forbidden in such cases.
Thanks for your assistance

**Comment by jdelStrother** [comment]
I'm not sure we've tried the OAuth API from a browser, so that might be something we need to fix.  We'll look into it.

**Comment by digitalillusion** [comment]
I'm now able to GET /account passing the Authorization header since lately the preflight request is being served correctly. Thank you very much!
