### ISSUE TITLE
Example POST format for file uploads

### ISSUE THREAD

**Issue by opn** [audioBoom/api#9]
Would it be possible to link the docs to an example of an authenticated multipart form encoded request? The docs are a bit sparse - and I am having difficulty figuring out exactly what the ruby code does. A link to pastebin or a gist showing some sample output would be great.

**Comment by jdelStrother** [comment]
Multipart uploads are a pain - you generally want to use a library to handle them for you.  The code here - https://github.com/audioBoom/audioboo-ruby-oauth/blob/master/audioboo-oauth-webapp.rb#L71-L81 - now shows how to use Faraday's multipart middleware to handle file uploads.
